package com.sample

import java.util.ArrayList;
import com.sample.DroolsTest.*;

declare Question
	question: String
	answers: ArrayList
	chosenAnswer: String
end

global GUI gui;

rule "Init"
	when
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("Yeah, they shmeoooke a bewrl");
		ans.add("No");
		insert(new Question("Uh... is there weed?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes, but I liked it before it was on Netflix");
		ans.add("No");
		insert(new Question("Is the show about hipsters?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("No, we're not");
		ans.add("Nailed it");
		insert(new Question("Are we talking about a sketch comedy?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("You know it");
		ans.add("Not unless you count James Van Der Beek");
		ans.add("No but that would be ah-MAH-zing");
		insert(new Question("3 words: Are there cupcakes?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yep");
		ans.add("Nope");
		insert(new Question("Do the characters own apartments they definitely can't afford?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		insert(new Question("Do the characters work for some kind of government agency?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		ans.add("Only if you count an ex-wife, amirite?");
		insert(new Question("Is there an evil queen?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Rich enough to be best friends with basically Oprah");
		ans.add("Poor enough to be best friends with a roller skating homeless dude");
		insert(new Question("Are the characters rich or poor?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		insert(new Question("Is the show set in the Northeast?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		insert(new Question("Are there kids on the show?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yeah...? That's a weird question");
		ans.add("No, and frankly it started getting ridiculous four seasons ago");
		insert(new Question("Do we know who everyone's mother is?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("No, nothing");
		ans.add("Yes, almost everything");
		ans.add("Only Walt's eyes, with the absolute corruption of his innermost soul");
		insert(new Question("Is stuff haunted?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		insert(new Question("Do the characters play sports?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes. Cars as luxurious as the woman you can never have.");
		ans.add("Who needs a car when you can ride a DRAGON?");
		insert(new Question("Do the characters use cars?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		insert(new Question("Do the characters use cell phones?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Big time");
		ans.add("No, thank God");
		insert(new Question("Do the characters sing a lot?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Every so often");
		ans.add("Never");
		ans.add("Literally all the time");
		insert(new Question("Roughly how often do people get shot?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		ans.add("Only if you count dazed employees");
		insert(new Question("Have there been zombies?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("Barely");
		ans.add("No. These characters are so white, they're frightened of the Irish");
		insert(new Question("Are there any black people?", ans, ""));
		
		ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		ans.add("No, but she thought she was");
		ans.add("What do you mean, \"during\"?");
		insert(new Question("Has a major character been pregnant during the show?", ans, ""));
		
		
end

rule "Doctor Who"
	when
		q: Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "What do you mean, \"during\"?")
	then
		gui.questionHandler("You're watching Doctor Who", null);
end

rule "Downtown Abbey"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "No. These characters are so white, they're frightened of the Irish")
	then
		gui.questionHandler("You're watching Downtown Abbey", null);
end

rule "The Office"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been zombies?", getChosenAnswer() == "Only if you count dazed employees")
	then
		gui.questionHandler("You're watching The Office", null);
end

rule "The Walking Dead"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been real zombies?", getChosenAnswer() == "Yes")
	then
		gui.questionHandler("You're watching The Walking Dead", null);
end

rule "Community"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been real zombies?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Community", null);
end

rule "Boardwalk Empire"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been zombies?", getChosenAnswer() == "No")
		Question(getQuestion()=="Roughly how often do people get shot?", getChosenAnswer() == "Every so often")
	then
		gui.questionHandler("You're watching Boardwalk Empire", null);
end

rule "Justified"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been zombies?", getChosenAnswer() == "No")
		Question(getQuestion()=="Roughly how often do people get shot?", getChosenAnswer() == "Literally all the time")
	then
		gui.questionHandler("You're watching Justified", null);
end

rule "Parenthood"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been zombies?", getChosenAnswer() == "No")
		Question(getQuestion()=="Roughly how often do people get shot?", getChosenAnswer() == "Never")
		Question(getQuestion()=="Do the characters sing a lot?", getChosenAnswer() == "No, thank God")
	then
		gui.questionHandler("You're watching Parenthood", null);
end

rule "Glee"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been zombies?", getChosenAnswer() == "No")
		Question(getQuestion()=="Roughly how often do people get shot?", getChosenAnswer() == "Never")
		Question(getQuestion()=="Covers or original songs?", getChosenAnswer() == "Covers. Horrible, horrible covers.")
	then
		gui.questionHandler("You're watching Glee", null);
end

rule "Smash"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Have there been zombies?", getChosenAnswer() == "No")
		Question(getQuestion()=="Roughly how often do people get shot?", getChosenAnswer() == "Never")
		Question(getQuestion()=="Covers or original songs?", getChosenAnswer() == "Originals. Horrible, horrible originals.")
	then
		gui.questionHandler("You're watching Smash", null);
end

rule "Game of Thrones"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters use cars?", getChosenAnswer() == "Who needs a car when you can ride a DRAGON?")
	then
		gui.questionHandler("You're watching Game of Thrones", null);
end

rule "Mad Men"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters use cars?", getChosenAnswer() == "Yes. Cars as luxurious as the woman you can never have.")
	then
		gui.questionHandler("You're watching Mad Men", null);
end

rule "The League"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are the sports real life or just fantasy?", getChosenAnswer() == "Fantasy")
	then
		gui.questionHandler("You're watching The League", null);
end

rule "Eastbound & Down"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are the sports real life or just fantasy?", getChosenAnswer() == "Real")
	then
		gui.questionHandler("You're watching Eastbound & Down", null);
end

rule "Breaking Bad"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Do the characters play sports?", getChosenAnswer() == "No")
		Question(getQuestion()=="Is stuff haunted?", getChosenAnswer() == "Only Walt's eyes, with the absolute corruption of his innermost soul")
	then
		gui.questionHandler("You're watching Breaking Bad", null);
end

rule "American Horror Story"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Do the characters play sports?", getChosenAnswer() == "No")
		Question(getQuestion()=="Is stuff haunted?", getChosenAnswer() == "Yes, almost everything")
	then
		gui.questionHandler("You're watching American Horror Story", null);
end

rule "Modern Family"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Do the characters play sports?", getChosenAnswer() == "No")
		Question(getQuestion()=="Is stuff haunted?", getChosenAnswer() == "No, nothing")
		Question(getQuestion()=="Do we know who everyone's mother is?", getChosenAnswer() == "Yeah...? That's a weird question")
	then
		gui.questionHandler("You're watching Modern Family", null);
end

rule "How I Met Your Mother"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Are there any black people?", getChosenAnswer() == "Barely")
		Question(getQuestion()=="Do the characters use cell phones?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Do the characters play sports?", getChosenAnswer() == "No")
		Question(getQuestion()=="Is stuff haunted?", getChosenAnswer() == "No, nothing")
		Question(getQuestion()=="Do we know who everyone's mother is?", getChosenAnswer() ==  "No, and frankly it started getting ridiculous four seasons ago")
	then
		gui.questionHandler("You're watching How I Met Your Mother", null);
end

rule "Bob's Burgers"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Is the show set in the Northeast?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Is there an evil queen?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Bob's Burgers", null);
end

rule "Once Upon a Time"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Is the show set in the Northeast?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Is there an evil queen?", getChosenAnswer() == "Yes")
	then
		gui.questionHandler("You're watching Once Upon a Time", null);
end

rule "Louie"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Is the show set in the Northeast?", getChosenAnswer() == "Yes")
		Question(getQuestion()=="Is there an evil queen?", getChosenAnswer() == "Only if you count an ex-wife, amirite?")
	then
		gui.questionHandler("You're watching Louie", null);
end

rule "Nashville"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Is the show set in the Northeast?", getChosenAnswer() == "No")
		Question(getQuestion()=="Could diaper changing be a legitimate plotline?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Nashville", null);
end

rule "Up All Night"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Is the show set in the Northeast?", getChosenAnswer() == "No")
		Question(getQuestion()=="Could diaper changing be a legitimate plotline?", getChosenAnswer() == "Unfortunately, yes")
		Question(getQuestion()=="Are the characters rich or poor?", getChosenAnswer() == "Rich enough to be best friends with basically Oprah")
	then
		gui.questionHandler("You're watching Up All Night", null);
end

rule "Raising Hope"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Is the show set in the Northeast?", getChosenAnswer() == "No")
		Question(getQuestion()=="Could diaper changing be a legitimate plotline?", getChosenAnswer() == "Unfortunately, yes")
		Question(getQuestion()=="Are the characters rich or poor?", getChosenAnswer() == "Poor enough to be best friends with a roller skating homeless dude")
	then
		gui.questionHandler("You're watching Raising Hope", null);
end

rule "Parks and Recreation"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for a SPY agency?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Parks and Recreation", null);
end

rule "Archer"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for a SPY agency?", getChosenAnswer() == "Danger zone!")
	then
		gui.questionHandler("You're watching Archer", null);
end

rule "Homeland"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for a SPY agency?", getChosenAnswer() == "I'm not at liberty to disclose that. Unless we're sleeping together.")
	then
		gui.questionHandler("You're watching Homeland", null);
end

rule "2 Broke Girls"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters own apartments they definitely can't afford?", getChosenAnswer() == "Yep")
		Question(getQuestion()=="3 words: Are there cupcakes?", getChosenAnswer() == "You know it")
	then
		gui.questionHandler("You're watching 2 Broke Girls", null);
end

rule "Apt 23"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters own apartments they definitely can't afford?", getChosenAnswer() == "Yep")
		Question(getQuestion()=="3 words: Are there cupcakes?", getChosenAnswer() == "Not unless you count James Van Der Beek")
	then
		gui.questionHandler("You're watching Apt 23", null);
end

rule "Happy Endings"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters own apartments they definitely can't afford?", getChosenAnswer() == "Yep")
		Question(getQuestion()=="3 words: Are there cupcakes?", getChosenAnswer() == "No but that would be ah-MAH-zing")
	then
		gui.questionHandler("You're watching Happy Endings", null);
end

rule "Portlandia"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters own apartments they definitely can't afford?", getChosenAnswer() == "Nope")
		Question(getQuestion()=="Are we talking about a sketch comedy?", getChosenAnswer() == "Nailed it")
		Question(getQuestion()=="Is the show about hipsters?", getChosenAnswer() == "Yes, but I liked it before it was on Netflix")
	then
		gui.questionHandler("You're watching Portlandia", null);
end

rule "Key & Peele"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters own apartments they definitely can't afford?", getChosenAnswer() == "Nope")
		Question(getQuestion()=="Are we talking about a sketch comedy?", getChosenAnswer() == "Nailed it")
		Question(getQuestion()=="Is the show about hipsters?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Key & Peele", null);
end

rule "Workaholics"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters own apartments they definitely can't afford?", getChosenAnswer() == "Nope")
		Question(getQuestion()=="Are we talking about a sketch comedy?", getChosenAnswer() == "No, we're not")
		Question(getQuestion()=="Uh... is there weed?", getChosenAnswer() == "Yeah, they shmeoooke a bewrl")
	then
		gui.questionHandler("You're watching Workaholics", null);
end

rule "Grimm"
	when
		Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "No")
		Question(getQuestion()=="Do the characters own apartments they definitely can't afford?", getChosenAnswer() == "Nope")
		Question(getQuestion()=="Are we talking about a sketch comedy?", getChosenAnswer() == "No, we're not")
		Question(getQuestion()=="Uh... is there weed?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Grimm", null);
end

rule "30 Rock"
	when
		Question(getQuestion()=="Was the character happy about her supposed pregnancy?", getChosenAnswer() == "So happy she lizzed her pants")
	then
		gui.questionHandler("You're watching 30 Rock", null);
end

rule "Veep"
	when
		Question(getQuestion()=="Was the pregnancy assumption unwelcome because she's only a girl?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Veep", null);
end

rule "Girls"
	when
		Question(getQuestion()=="Was the supposedly pregnant girl adorkable?", getChosenAnswer() == "No")
	then
		gui.questionHandler("You're watching Girls", null);
end

rule "New Girl"
	when
		Question(getQuestion()=="Was the supposedly pregnant girl adorkable?", getChosenAnswer() == "Are you happy now commercials? We're using your dumb made-up word.")
	then
		gui.questionHandler("You're watching New Girl", null);
end

rule "Real Zombies"
	when
		q: Question(getQuestion()=="Have there been zombies?", getChosenAnswer() == "Yes")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		insert(new Question("Have there been real zombies?", ans, ""));
end

rule "Covers or original songs"
	when
		q: Question(getQuestion()=="Do the characters sing a lot?", getChosenAnswer() == "Big time")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("Originals. Horrible, horrible originals.");
		ans.add("Covers. Horrible, horrible covers.");
		insert(new Question("Covers or original songs?", ans, ""));
end

rule "Real life sports or fantasy"
	when
		q: Question(getQuestion()=="Do the characters play sports?", getChosenAnswer() == "Yes")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("Fantasy");
		ans.add("Real");
		insert(new Question("Are the sports real life or just fantasy?", ans, ""));
end

rule "Diaper changing"
	when
		q: Question(getQuestion()=="Are there kids on the show?", getChosenAnswer() == "Yes")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("Unfortunately, yes");
		ans.add("No");
		insert(new Question("Could diaper changing be a legitimate plotline?", ans, ""));
end

rule "SPY agency"
	when
		q: Question(getQuestion()=="Do the characters work for some kind of government agency?", getChosenAnswer() == "Yes")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("Danger zone!");
		ans.add("I'm not at liberty to disclose that. Unless we're sleeping together.");
		ans.add("No");
		insert(new Question("Do the characters work for a SPY agency?", ans, ""));
end

rule "Happy about pregnancy"
	when
		q: Question(getQuestion()=="Has a major character been pregnant during the show?", getChosenAnswer() == "No, but she thought she was")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("No");
		ans.add("So happy she lizzed her pants");
		insert(new Question("Was the character happy about her supposed pregnancy?", ans, ""));
end

rule "Because she's only a girl"
	when
		q: Question(getQuestion()=="Was the character happy about her supposed pregnancy?", getChosenAnswer() == "No")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("Yes");
		ans.add("No");
		insert(new Question("Was the pregnancy assumption unwelcome because she's only a girl?", ans, ""));
end

rule "Adorkable"
	when
		q: Question(getQuestion()=="Was the pregnancy assumption unwelcome because she's only a girl?", getChosenAnswer() == "Yes")
	then
		ArrayList<String> ans = new ArrayList<>();
		ans.add("No");
		ans.add("Are you happy now commercials? We're using your dumb made-up word.");
		insert(new Question("Was the supposedly pregnant girl adorkable?", ans, ""));
end

rule "Q"
	when
		q: Question( getChosenAnswer() == "" )
	then
		System.out.println(q.getQuestion());
		String answer = gui.questionHandler(q.getQuestion(), q.getAnswers());
		q.setChosenAnswer( answer );
		update( q );
		System.out.println("> " + q.getChosenAnswer());
end